const KEY='glimmerfics-hogwarts-v1';
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{node:'start',name:'Samira Wellington',pronouns:'',appearance:'',sebastian:0,ominis:0,anne:0,custom:[]};
const $=s=>document.querySelector(s); const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const nodes={
start:{loc:'Ravenclaw Tower · The Morning After',text:[`Grey morning light filters through the tall windows of Ravenclaw Tower. For a moment, you lie perfectly still, listening to Hogwarts wake around you.`,`Then the memory returns: your father's letter, the resonance chamber, Sebastian's diagram, and Ominis's quiet promise to help you reach the Gaunt vault.`,`Two days before Hogsmeade weekend. Two days to prepare. And somewhere beyond the castle walls, Anne Sallow is still waiting for a cure.`],choices:[['Go to breakfast early and look for Sebastian and Ominis.','breakfast'],['Head to the library first. You need to study the diagram.','library'],['Find Professor Sharp and ask about resonance magic.','sharp'],['Return to the hidden balcony and think.','balcony']]},
breakfast:{loc:'Great Hall',text:[`The Great Hall is already loud when you arrive. Owls sweep overhead, plates clatter, and the morning sun turns the enchanted ceiling a pale winter blue.`,`You spot Sebastian first. He is pretending to eat while reading a folded piece of parchment beneath the table. Ominis sits opposite him, wand resting against his palm.`,`Sebastian looks up. His expression changes the instant he sees you. “Wellington. Finally.”`],choices:[['Sit beside Sebastian. “You look like you have not slept.”','seb'],['Sit beside Ominis. “Have you finished the vault plan?”','omi'],['Sit between them. “Show me everything.”','both'],['Ask about Anne first. “How is she?”','anne']]},
seb:{loc:'Great Hall',text:[`Sebastian folds the parchment and gives you a look that is half amusement, half relief. “I slept. Mostly.”`,`He lowers his voice. “The diagram changed overnight. I think your father's frequency can do more than stabilize Anne. I think it can reverse part of the curse.”`,`His eyes hold yours for a beat too long. “But I need you there when we test it.”`],choices:[['“Then I will be there.”','library'],['Touch his hand briefly. “We will save her.”','romseb'],['“You are not doing this alone.”','both']]},
romseb:{loc:'Great Hall',text:[`Your fingers close around his for only a moment. Sebastian goes very still. Then his thumb shifts against yours, almost unconsciously.`,`“Right,” he murmurs. “We will.”`,`Across the table, Ominis clears his throat. “I assume breakfast is still happening.”`,`Sebastian releases your hand, but the warmth remains.`],choices:[['Smile at Ominis. “You are right. We need food.”','library'],['Meet Sebastian’s eyes again. “Later?”','library']]},
omi:{loc:'Great Hall',text:[`Ominis turns slightly toward you. His wand pulses once as if confirming exactly where you are.`,`“The plan is ready in principle. The difficulty is the blood wards. They respond to family magic, and I have spent years trying not to become part of that family again.”`,`His voice softens. “But if the journal is there, it may tell us how your father's resonance work connects to Anne's curse.”`],choices:[['“Thank you for trusting me.”','romomi'],['“Then we go together.”','library'],['“You do not have to face your family alone.”','both']]},
romomi:{loc:'Great Hall',text:[`For a second, Ominis says nothing. His fingers tighten around his wand.`,`“That,” he says quietly, “is a dangerous thing to promise someone like me.”`,`Yet there is the smallest curve at the corner of his mouth. “I would not object to you keeping it.”`],choices:[['“Good. Because I meant it.”','library'],['Change the subject before your face gives you away.','library']]},
both:{loc:'Great Hall',text:[`You spread Sebastian's diagram beside Ominis's notes. The three of you lean over the parchment while the Great Hall moves around you.`,`The pieces fit with unsettling precision: your father's resonance pattern, Sebastian's stabilization theory, and an old Gaunt reference to a chamber beneath their family vault.`,`For the first time, the path toward Anne feels like something more than hope.`],choices:[['“We find the chamber. Then we save Anne.”','library'],['Ask Sebastian to explain his part of the pattern.','seb'],['Ask Ominis to explain the Gaunt reference.','omi']]},
library:{loc:'Library · Restricted Section',text:[`By midday, the library has become your command post. Books surround the three of you in uneven towers.`,`Sebastian has drawn a cleaner version of the frequency diagram. Ominis has located three references to resonance chambers hidden in old family records.`,`The final piece is missing: a method of activating the chamber without allowing its echo to permanently mark the caster.`],choices:[['Study the activation sequence yourself.','study'],['Ask Sebastian to test the sequence with you.','testseb'],['Ask Ominis to listen for a flaw in the resonance.','testomi'],['Search the Restricted Section for another reference.','restricted']]},
study:{loc:'Library · Restricted Section',text:[`You trace the symbols with your quill. The pattern seems almost familiar—not because you have seen it before, but because your magic recognizes the shape.`,`The parchment gives a faint hum beneath your fingers.`,`Sebastian's voice drops. “Samira?”`,`The hum stops.`],choices:[['Tell them exactly what you felt.','truth'],['Hide the reaction and keep studying.','hidden'],['Place your wand over the diagram.','wand']]},
truth:{loc:'Library · Restricted Section',text:[`You explain the resonance. Ominis listens without interrupting. Sebastian watches you with an intensity that makes it difficult to look away.`,`“Then the chamber may recognize you,” Ominis says. “Which means you may be the only person who can safely activate it.”`,`Sebastian's jaw tightens. “Or the person it is waiting for.”`],choices:[['“Then I will activate it.”','chamber'],['“We find another way first.”','prepare']]},
hidden:{loc:'Library · Restricted Section',text:[`You keep your reaction to yourself. The symbols remain stubbornly silent.`,`Sebastian eventually leans closer. “You are doing that thing again.”`,`“What thing?”`,`“Pretending you are fine when you are clearly thinking about something dangerous.”`],choices:[['Admit what you felt.','truth'],['“I am fine. Help me with the next symbol.”','prepare']]},
wand:{loc:'Library · Restricted Section',text:[`You place your wand against the center of the pattern. A low vibration travels through your hand.`,`Ominis's head lifts instantly. “There.”`,`Sebastian whispers, “That is the same frequency.”`,`The diagram illuminates for a heartbeat, revealing a hidden line beneath the ink: a map to the chamber.`],choices:[['Follow the map immediately.','chamber'],['Copy the map first. We need a backup.','prepare']]},
testseb:{loc:'Undercroft',text:[`The Undercroft is cold and still. Sebastian sets the diagram on the floor and draws the first line of the sequence.`,`“If this works,” he says, “the pulse should last three seconds.”`,`You stand opposite him, wand raised. “And if it does not?”`,`He smiles faintly. “Then we learn something.”`],choices:[['Cast the sequence with him.','chamber'],['Stop him. “We need a safer test.”','prepare']]},
testomi:{loc:'Undercroft',text:[`Ominis kneels beside the diagram, fingertips hovering above the parchment.`,`“Do not cast yet,” he says. “There is a second resonance underneath the first.”`,`Sebastian frowns. “I cannot hear it.”`,`“I can.” Ominis turns toward you. “And so can your wand.”`],choices:[['Trust Ominis and follow the secondary resonance.','wand'],['Ask Sebastian to compare the symbols again.','prepare']]},
restricted:{loc:'Restricted Section',text:[`Deep in the Restricted Section, you find a damaged volume describing “echo chambers”—places where magic can retain the intention of a spell long after the caster leaves.`,`One line stops you cold: the safest anchor is not the strongest wizard, but the one whose magic the chamber already recognizes.`],choices:[['Take the book to Sebastian and Ominis.','truth'],['Keep the passage to yourself for now.','hidden']]},
prepare:{loc:'Library · Late Evening',text:[`You spend the evening preparing rather than rushing. The decision feels small, but it changes something between the three of you.`,`Sebastian stops trying to solve everything in a single night. Ominis maps the safest route. You copy every symbol twice.`,`Anne is still the reason for all of it. But now there is a plan.`],choices:[['Go to sleep and meet them before breakfast.','chamber'],['Stay up with them a little longer.','late']]},
late:{loc:'Library · Late Evening',text:[`The library grows quiet. Sebastian sits close enough that your shoulders nearly touch. Ominis rests against a shelf, listening to the castle breathe.`,`“When this is over,” Sebastian says, “I want to see what you do when you are not trying to save someone.”`,`Ominis's voice comes from the dark. “And I would like to know what you choose when there is nothing forcing you to choose.”`,`Neither of them laughs.`],choices:[['“You both make it very difficult to think.”','chamber'],['Reach for Sebastian’s hand.','romseb2'],['Turn toward Ominis. “What would you choose?”','romomi2']]},
romseb2:{loc:'Library · Late Evening',text:[`You find Sebastian's hand beside you. His fingers close around yours, careful at first, then certain.`,`He does not make a joke. “Samira,” he says quietly, “after Anne is safe, I want to talk about this.”`,`You squeeze his hand. “After Anne is safe.”`],choices:[['Keep holding his hand.','chamber'],['Let go, but smile.','chamber']]},
romomi2:{loc:'Library · Late Evening',text:[`Ominis is silent for a long moment.`,`“I would choose the person who makes me want to be better than my family,” he says. “That is all I know.”`,`His wand pulses once. You realize he has turned fully toward you.`],choices:[['“Then perhaps we should talk after Anne is safe.”','chamber'],['Reach toward him, giving him the choice to close the distance.','chamber']]},
chamber:{loc:'Hidden Chamber · Beneath Hogwarts',text:[`The map leads beneath the oldest foundations of Hogwarts. The stone door opens only when your wand touches the final symbol.`,`Beyond it, an ancient chamber hums with the same frequency as your father's notes. The air seems to listen.`,`Sebastian looks at you. Ominis grips his wand. Somewhere far away, a clock strikes midnight.`],choices:[['Step into the chamber and activate the resonance.','ending'],['Ask Sebastian to stand beside you.','endingseb'],['Ask Ominis to anchor the spell.','endingomi']]},
ending:{loc:'Hidden Chamber',text:[`You step forward. The chamber answers. Light moves through the walls in concentric waves, carrying your father's frequency into the stone.`,`For one breath, you feel another presence—an echo, not a ghost. A memory of the man who left this path for you.`,`The resonance locks. Somewhere in Feldcroft, Anne's curse shudders.` ,`It is not the cure. Not yet. But for the first time, the curse has stopped advancing.`],choices:[['“We have a starting point.”','end'],['Reach for both boys. “Together.”','end']]},
endingseb:{loc:'Hidden Chamber',text:[`Sebastian steps to your side. Your magic meets his, and the chamber's pulse steadies.`,`“Anne,” he whispers. The word is a promise.`,`The resonance travels through the chamber and out beyond Hogwarts. The curse does not break—but it weakens.`],choices:[['“Now we finish what my father started.”','end']]},
endingomi:{loc:'Hidden Chamber',text:[`Ominis raises his wand and listens. You follow the rhythm he gives you. Sebastian completes the sequence.`,`Three magics, one frequency. The chamber opens fully.`,`The resonance reaches Anne. Her curse does not vanish, but the decay stops.`],choices:[['“She has time now.”','end']]},
end:{loc:'End of Episode II · The Resonance',text:[`The three of you stand in the silent chamber, exhausted and shaken. Anne has time now. That is enough for tonight.`,`But your father's letter warned you: the chamber listens. And now it knows you.`,`Tomorrow, you will begin the search for the complete cure.`],choices:[]}
};
const effects={seb:()=>state.sebastian++,romseb:()=>state.sebastian+=2,romseb2:()=>state.sebastian+=3,omi:()=>state.ominis++,romomi:()=>state.ominis+=2,romomi2:()=>state.ominis+=3,anne:()=>state.anne++};
function render(id=state.node){state.node=id;save();const n=nodes[id];$('#location').textContent=n.loc;$('#progress').textContent=id==='end'?'Episode II · Complete':'Episode II';$('#story').innerHTML=n.text.map(x=>`<p>${x}</p>`).join('');const box=$('#choices');box.innerHTML='';n.choices.forEach((c,i)=>{const b=document.createElement('button');b.className='choice';b.innerHTML=`<span class="num">${i+1}</span><span>${c[0]}</span>`;b.onclick=()=>go(c[1]);box.appendChild(b)});$('#customForm').style.display=n.choices.length?'block':'none';$('#relationshipState').textContent=`Sebastian · ${state.sebastian}  |  Ominis · ${state.ominis}  |  Anne · ${state.anne}`;window.scrollTo({top:0,behavior:'smooth'})}
function go(id){effects[id]?.();render(id)}
$('#customForm').onsubmit=e=>{e.preventDefault();const v=$('#customChoice').value.trim();if(!v)return;state.custom.push({at:state.node,text:v});$('#customChoice').value='';state.node='custom';save();renderCustom(v)};
function renderCustom(v){const old=nodes[state.node];$('#location').textContent='Your Choice';$('#progress').textContent='Episode II';$('#story').innerHTML=`<p>You choose to: <span class="thought">${escapeHtml(v)}</span></p><p>The castle seems to shift around your decision. The story bends, but the path toward Anne remains.</p>`;$('#choices').innerHTML='';[['Continue toward the library','library'],['Go to Sebastian and Ominis','both'],['Follow the hidden resonance','chamber']].forEach((c,i)=>{const b=document.createElement('button');b.className='choice';b.innerHTML=`<span class="num">${i+1}</span><span>${c[0]}</span>`;b.onclick=()=>go(c[1]);$('#choices').appendChild(b)});$('#relationshipState').textContent=`Sebastian · ${state.sebastian}  |  Ominis · ${state.ominis}  |  Anne · ${state.anne}`}
function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
$('#restart').onclick=()=>{if(confirm('Restart this story from the beginning?')){localStorage.removeItem(KEY);location.reload()}};render();
